server:
  port: 8001
spring:
  application:
    name: provider-8001
  rabbitmq:
    host: 8.140.171.57  #你的rabbitmq服务器地址
    port: 5672
    username: root
    password: H03089611.
    virtual-host: test
    listener:
      simple:
        default-requeue-rejected: false


